### ISSUE TITLE
Standard angular-schema-form controls broken, e.g. select doesn't use enum values

### ISSUE THREAD

**Issue by TrevorPage** [OptimalBPM/angular-schema-form-dynamic-select#14]
I use ASF (in its standard form) to provide select menus driven from the `enum` property in the schema. For example:

```
    $scope.schema = {
        type: "object",
        title: "Animals",
        properties: {
            A_select: {
                title: "Animals",
                type: "string",
                description: "some description",
                   "enum": [
                        "Dogs", "Cats", "Fish"
                    ]
            },

...

    $scope.form = [
        {
            "key": "A_select",
            "type": "select"
        },

...
```

When adding in the angular-schema-form-dynamic-select library, I have to add the explicit `"type": "select"` property. Before adding ASFDS, the ASF library would by default imply a 'select' by the fact that the schema is a `string` with an `enum` propery. After adding ASFDS, I have to add the `type` property as otherwise every property (even simple string fields) become an 'empty' select that displays `placeholders.select`.

The main issue however is that `select`s' options are no longer populated using the schema's `enum` property. So, given the above code example, the Dogs / Cats / Fish options don't appear in the select, and it just displays  `placeholders.select`.

To try to eliminate some mistake in my own application, I have taken the entire example at http://demo.optimalbpm.se/angular-schema-form-dynamic-select/ with all specific script versions it uses, confirmed it all worked beforehand, and then added my additional select as shown above into it. Unfortunately the result was same behaviour as above. 

I was under the impression I could add ASFDS and all existing ASF code would work as before, and the new select controls would only be generated if I explicitly specified one of the new `type`s. Is this not the case?

Hopefully this is something daft I'm doing on my part. Thank you for your efforts you put into this library!

**Comment by nicklasb** [comment]
You are completely right:
1.  No, It doesn't use the enum field:
   A shortcoming with using enum in a UI is that it doesn't have any value/text format, and the common use case that the descriptive name actually isn't the same as the value(besides Id:s, consider translations, for example). But obviously I see where you come from, it would be redundant to describe them in both and it would be weird to have them conflicting. 
2. Yes, you have to add the "type" property. 
   This is currently by design as there are several modes of selects provided by ASFDS and then the default behavior could become more confusing than not having it at all. 
   I presume that is the case, least, I wasn't around at the time that was written.

That it interferes with all the other fields is a problem. However, It just occurred to me that there was some problem with how something worked with the ASF decorator defaults. I'll be back on that one.

Anyway, my opinions certainly aren't very strong about these things, so if I understand this correctly, it would work as you want if I added the following:
If there is no options.items, use the enum field and populate a single select with the same value and text values.  (single as there is no "multiple" in the ASF select, it seems)

Am I right?

**Comment by nicklasb** [comment]
Hi, If you look at the develop branch and the first drop down of the demo there, I have now done so that the strapselect uses the enum from the schema if no options.items is set.

Note: I am doing this for only the single-select non-callback strapselect, since json.schema enum is non-multiple and schema.enum is static.

**Comment by TrevorPage** [comment]
Hi Nicklas!

Firstly thank you so much for commenting on this and making a proposed change so soon! That was a nice surprise!

In our application, it is important that the actual schema holds the enum values, because the schema has to define what options are available in a select menu. We would be unable to embed the options within the UI. Furthermore, I perform language translation to the `form` object in `schemaFormProvider.postProcess()`, at which point I translate the `name` properties in all of the `titlemaps`s. I actually use the 'raw' enum value as the key for translation. Therefore I would very much agree with your proposal that the schema's enum property is used (standard ASF behaviour), but this could be overridden by the inclusion of value/text properties. 

Regarding the 'type' property, I think it is important for this not to be mandatory and for the standard ASF defaults to be used if it isn't included. It's not so much work for me to add the 'type' properties into my forms, but it breaks far too much of the standard behaviour of ASF, and also it means that you can no longer describe a form using simply `["*"]` if you wanted to. In particular it makes no sense that a simple 'string' becomes a select menu rather than a text field unless you explicitly say it's a 'type' of 'string'. 

As things presently stand, including ASFDS into my existing ASF project breaks a lot of standard ASF behaviour. What would be very nice, and quite critical in fact, would be for ASFDS to behave such that all existing ASF code works as before, and ASFDS only kicks in and provides special new select menus if they are explicitly requested by the `type`. 

What I have done today is I have written a small function which generates the value/text object from the enum property in the schema. It's a little ugly, but it works for now. I have also added `type` properties in all the forms. What I will do now though is give your develop branch a try!

This is my first proper Angular project by the way, and I'm really loving working with all these libraries. Thank you so much for your work. I hope I can contribute code to it one day.

Trev

**Comment by nicklasb** [comment]
No problem, I am using it heavily, and the enum thing was a problem that had to be addressed.

Actually, the type property should _not_ be mandatory as it is now. I have actually no idea why it is, I am trying to figure that out right now. Will probably have to talk to the ASF guys about that.

And not in defence of how ASFDS works, and meaning no offence, as this is according to my collected experience: But using the likes of ["*"] and relying on different default behaviors from any library in production code is something I cannot discourage enough. 

It is always worth it to take that control, because defaults often depend on other defaults, which makes it so that even subtle changes in any underlying library can render an application completely unusable. Also, bugs concerning default values are always lowly prioritized because they are so easily worked around and if you have based your application around them, that code will go into the core and always be ugly.

One should take the hint from the ASF docs, the form defaults section, ["Its recommended to split presentation and validation into a form definition and a json schema."](https://github.com/Textalk/angular-schema-form/blob/development/docs/index.md#form-defaults-in-schema)

If you follow that advice, it will follow that UI defaults are only relied upon in prototyping and initial tests.

**Comment by nicklasb** [comment]
BTW, I heavily edited the above post, so if you reading this on e-mail, read it on git hub.. sorry.

**Comment by nicklasb** [comment]
Ok, do a git pull and check again, I finally fixed the type-bug, too. 
Now only fields with enum value or arrays are overridden by default.

**Comment by nicklasb** [comment]
What the h*ll, I realized that there is no reason for the component to not be totally harmonized with ASF.
So now it is. It now also uses titleMap instead of "items.

So now It should work as a drop-in replacement, as you wanted.
Could you please test with your stuff, and then I can make a release?

**Comment by nicklasb** [comment]
I had to go to bed and everything seemed to work, so made a 0.8.0 release that has all those changes:
https://github.com/OptimalBPM/angular-schema-form-dynamic-select/releases/tag/v0.8.0

Please check it out with your stuff, no need to use the develop branch.

**Comment by TrevorPage** [comment]
Many thanks. I have just included the 0.8.0 version and removed the workarounds I had in place for 0.7.0.

With regards to the `type` property, so far it seems harmonised with ASF. For example, string fields in the schema without enums are represented as a text field. 

Regarding the main issue of standard `select` types and schema enums, it seems to be half working. Specifically, any select which _isn't_ in an array now works as it did before (no explicit `type` needed; 'select' is inferred, and values derived, from the presence of enums in the schema). So far so good. But, I have some selects contained in an array of items, and those selects are broken. I have temporarily removed ASFDS and find that those selects start working again when I do that.

Here is example code that has the same structure as my real code:

The form definition:

```
  $scope.form_priority = [
      {
          "key": "PRIORITIES.PRIORITY",
          "add": null,
          "type": "array",
          "remove": null,

          "items": [{
              "type": "select",
              "key": "PRIORITIES.PRIORITY[].VALUE"
          }]
      }
  ];
```

The schema:

```
var schemaArc = {

  "type": "object",
  "properties": {

    "PRIORITIES": {
        "type": "object",
        "properties": {
          "PRIORITY": {
            "type": "array",
            "items": {
              "type": "object",          
              "properties": {       
                "VALUE": {
                  "type": "string",
                  "enum": [ "DOG", "CAT", "FISH" ]
                };
              }
            }
          }
        }
      },


  }
};
```

model:

```
"PRIORITIES": {
      "PRIORITY": [
        {
          "$": {
            "id": "0"
          },
          "VALUE": "DOG"
        },
        {
          "$": {
            "id": "1"
          },
          "VALUE": "DOG"
        },
        {
          "$": {
            "id": "2"
          },
          "VALUE": "FISH"
        }
      ]
    },

```

The expected behaviour is that three rows are generated, each containing a select with DOG, CAT, FISH options. From the above model, these would initially be DOG, DOG, FISH. This is the behaviour seen with standard ASF. With ASFDS included ('mgcrea.ngStrap' added to the angular.module and 0.8.0 ASFDS .js included), the behaviour is that those selects are blank and contain no options.

**Comment by TrevorPage** [comment]
For completeness, I should probably mention that the above code, plus other code which creates single selects (which work as explained) is repeated in an outer tab array. 

In other words, picture a tab array, where each tab pane contains the above array of selects, plus some other non-array selects. It may not be relevant, but thought I'd mention it, as the issue does seem to be something to do with arrays.

**Comment by nicklasb** [comment]
Strange, I'll have a look.

**Comment by nicklasb** [comment]
BTW, I don't think I am replacing the standard select if the type actually says "select" in the form.

**Comment by TrevorPage** [comment]
If it's any use, I tried making the form reference just one instance of the select:

```
  $scope.form_priority = [
      {
              "key": "PRIORITIES.PRIORITY[0].VALUE"
      }
]
```

With that, I got a text field control, with the text of one of the options.

If I added `"type" : "select"`, then the control changed from a text field to an empty select.

I also notice that in either case above, `$scope.findTitles` isn't being called. 

Presumably it isn't properly inferring select because it's not seeing the enum property when the key contains several JSON nodes or array nodes?

**Comment by TrevorPage** [comment]
`$scope.findTitles` _is_ called however for other selects which do work, those selects being those that have a simple JSON key because they are right in the 'root' of the schema. E.g. `[ "ANIMALS" ]`

**Comment by nicklasb** [comment]
Ok, I am looking around, and there is something strange in how ASF handles forms in items in arrays, as well. 
If you explicitly sets "select" as type, then ASFDS should not be involved at all.

**Comment by TrevorPage** [comment]
OK. Just to confirm:

If I explicitly set type "select", the problematic select is a native select element as you state it should be, only it isn't being populated from the enums by ASF (unless I remove ASFDS).

If I remove the type "select", then ASFDS provides a text field, rather than providing a Bootstrap select.

**Comment by nicklasb** [comment]
Ok. I just released a bug fix release that among other things removes some unnecessary defaults.
I don't know if that helps with this problem, but at least it removes those bugs from the equation.
Could you please try with that?

**Comment by nicklasb** [comment]
That thing with the select type is just plain weird.

**Comment by TrevorPage** [comment]
OK, I will try that right now!

Also I don't know if it's any help, but I have just replicated the problem inside your own app.js demo by adding my example above into it. I expect you've already done this but I'm happy to send it to you if you let me know the best way to chuck it over.

**Comment by TrevorPage** [comment]
I'm afraid the behaviour is still the same with the latest release (0.8.1, presumably).

**Comment by nicklasb** [comment]
Great! If it doesn't help, please do! 
Send it to _deleted_
(i'll edit the email away when you've sent it)

**Comment by TrevorPage** [comment]
OK - just done.

**Comment by nicklasb** [comment]
If I add the following to the asf example(http://schemaform.io/examples/bootstrap-example.html):
Form:

```
[   
  {
    "key": "PRIORITIES.PRIORITY[0].VALUE",
    "type" : "select"
  }
]   
```

Schema:

```
{
    "type": "object",
    "title": "Select",
    "properties": {       
        "PRIORITIES": {
            "type": "object",
            "properties": {
              "PRIORITY": {
                "type": "array",
                "items": {
                  "type": "object",          
                  "properties": {       
                    "VALUE": {
                      "type": "string",
                      "enum": [ "DOG", "CAT", "FISH" ]
                    }
                  }
                }
              }
            }
        }

    }
}
```

...It is also ending up with an empty select.

**Comment by nicklasb** [comment]
Aha, it seems that ASF do not understand the [0]-notation. 
I am not sure that you can tell it that a form field references a certain item.

**Comment by TrevorPage** [comment]
Oops, apologies - I was _sure_ I confirmed that notation worked; I think I've confused myself trying to rush around.

What I confirm does work in an array is this:

```
  $scope.form_priority = [
    {
        "key": "PRIORITIES.PRIORITY",
        "add": null,
        "type": "array",
        "remove": null,
        "items": [
            { 
                "type" : "select",
                "key": "PRIORITIES.PRIORITY[].VALUE"                                    
            }
        ]
    }
  ];
```

**Comment by nicklasb** [comment]
No problem. Especially since It seems that I forgot to build the 0.8.1-version properly, so the defaults are still in there. :-)

Yes, the []-kind works.

**Comment by TrevorPage** [comment]
What I have just done now is I've further modified your demo app.js so that it tries to build an array of selects using the snippet above. 

The above code 100% works in my application (with plain ASF), but in the demo app.js what we see is:
- without explicit select: An array of text fields, populated with the model strings.
- with explicit select: An array of empty native select controls. 

I will send the modified app.js now.

**Comment by TrevorPage** [comment]
Oh, ha - I'll try the 0.8.1 again in a minute in that case! 

Actually lunch first. :hamburger:

**Comment by nicklasb** [comment]
No, don't try it. And yes, go take a bite. For some reason removing the defaults seems to be breaking ASF... I'll be back.

**Comment by nicklasb** [comment]
So..I have now released 0.8.2, that seems to fix everything. 
What had happen was that the build had not happened completely when I tested the code, so everything seemed to work, which it didn't. 
0.8.1 actually fixed the problem, but broke the examples and tests, that had to be changed.
I have _almost_ added your priorities-example to app.js, it seems that the other parts of the app.js broke things before it got to your stuff.
If you remove the items definitions and does like below, it works with the defaults:

```
    {
        "key": "priorities.priority",
        "type" : "array"

    }
```

Also this works. 

```
"key": "priorities.priority[].value"
```

**Comment by TrevorPage** [comment]
With just the key specified and the type omitted, it does indeed now work! Thank you so much for your work on this. The negative news however is that 0.8.2 seems to have broken an `strapmultiselectdynamic` (using `asyncCallback`) which was working just fine on 0.8.1.

**Comment by TrevorPage** [comment]
Ah, adding in the `items: { type:"string"},` into the schema got my dynamic multi select working again. I saw in your changes that it's now required. So, all actually seems good now!

**Comment by nicklasb** [comment]
Yes, ASFDS no longer defaults over the array type, so now the type of items has to be defined in the schema. Which is actually how it is supposed to work, BTW. 
I had simply forgot that before as the overzealous defaulting hid that problem.

**Comment by nicklasb** [comment]
If there is nothing left that doesn't work, I am closing this issue now.

**Comment by TrevorPage** [comment]
I will keep testing as I work on this and let you know immediately if there's anything else. Again, thanks for being able to work on this so quickly.

**Comment by nicklasb** [comment]
No problem, thanks for your testing and feedback, that is just as important.

**Comment by TrevorPage** [comment]
I think there is still a problem. When ASFDS is in use, it seems that ordinary ASF `select`s are broken. In other words, if I explicitly state `type=select` in the `$scope.form`, with the hope of producing an ordinary ASF select, what I get is a select which only has one empty option. It does not contain any of the options supplied by the `enum` property in the schema.

The reason I am trying to do this, rather than using ASFDS selects everywhere, it because on one particular page I want to use a slightly customised decorator for an ordinary select. So, I have taken the ASF `angular-schema-form/src/directives/decorators/bootstrap/select.html` and tweaked it, and then registered under a new type name `selectWithIndex`. The reason for doing this is because what I require is for the `label` to be suffixed with the array number. This is so that I can produce an array of selects where the labels are like "label 1", "label 2", and so on.

Example:

```
    $scope.form = [ 
        {
            "key" : "TESTFIELD"//,
            //"type" : "select"
        },


schema: 
 {
    "TESTFIELD": {
        "type": "string",
        "enum": [ "DOG", "CAT", "FISH" ]       
    }
```

With ASFDS plugged in, the above will create a working ASFDS select that works. 

If the type:select is uncommented then I get an empty ASF select (or more accurately a select with a single empty option).

If I then remove ASFDS then the ASF select is populated with the options.

Is this accidental or intended behaviour?

This might be a somewhat moot issue now anyway, because I've also found that the normal ASF select doesn't work properly in that when the form is first rendered, the select shows the blank option rather than defaulting to the current model value. I've raised an issue with ASF here: https://github.com/Textalk/angular-schema-form/issues/462

Therefore I might just have to abandon the custom decorator idea and use some hacky jQuery to loop through and append indices to the labels.

**Comment by nicklasb** [comment]
Ok, I think understand your problem.

No, that is certainly not intended behaviour, ASFDS should not interfere with the standard select if "select" is specified. 
I have no idea why, though, schemaFormProvider.defaults should not be consulted if the form type is set, so ASFDS should not be involved in any way. 

I'll have to look into this.

**Comment by nicklasb** [comment]
I have confirmed this in the example with the develop branch. Weird.

**Comment by nicklasb** [comment]
The problem seems to be with ASF. The built-in ASF select only calls enumToTitleMap() when it is invoked via default schema types, and when ASFDS is used, it hides this problem. 
Closing this issue, see https://github.com/Textalk/angular-schema-form/issues/462 for a resolution.

**Comment by TrevorPage** [comment]
Thank you for looking into this! :+1:
